Included id_token_jwt in token response
OpenIDC/pyoidc pull request #805
Opened 2022-03-27 10:54 UTC by infohash

The ID token JWT needs to be passed in the access token response to be usable as id_token_hint for RP-Initiated Logout. Refer to [RP-Initiated Logout](https://openid.net/specs/openid-connect-rpinitiated-1_0.html#RPLogout) specification.

The existing code replaces JWT with the verified IdToken instance but it should be preserved. I've added `id_token_jwt` which stores signed and serialised ID token.

2022-05-02 07:29 UTC, tpazderka requested changes
The quality check is failing.

2022-05-02 16:11 UTC, infohash commented
@tpazderka Merged from upstream. Now all test cases are passing. Can you fix the failing job of build (3.6):

```
ERROR:   py36: commands failed
SKIPPED:  py37: InterpreterNotFound: python3.7
  py38: commands succeeded
  docs: commands succeeded
  quality: commands succeeded
Error: Process completed with exit code 1.
```

2022-05-03 11:46 UTC, tpazderka commented
Yeah, I have decided to drop 3.6 so that should fix the issue :)

2022-05-04 07:14 UTC, tpazderka approved these changes

2022-05-04 07:19 UTC, closed without merging