Fixed parsing for zero content length response
OpenIDC/pyoidc pull request #812
Opened 2022-05-06 07:47 UTC by infohash

The `content-type` in the header is optional when the payload has zero content length. See, [Should Content-Type header be present when the message body is empty?](https://stackoverflow.com/questions/29784398/should-content-type-header-be-present-when-the-message-body-is-empty).

This happens when the request to IdP is made for revoking tokens. In that case, IdP returns a `200 OK` status code with no body and no  `Content-Type` in the response header.

See, [About the revoke request](https://developer.okta.com/docs/guides/revoke-tokens/main/#about-the-revoke-request).

> Revoking a token that is invalid, expired, or already revoked returns a 200 OK status code to prevent any information leaks.

To parse responses with zero content length, just check if the value of `content-length` is 0 and return the status code if it does.

2022-05-06 08:00 UTC, tpazderka requested changes
The new code should be covered by tests.

2022-05-10 06:40 UTC, tpazderka requested changes
The tests should be unittests, so you should write a test for `parse_request_response` and `verify_header` functions that cover the changes introduced here.

2022-05-12 09:14 UTC, infohash commented
@tpazderka Awaiting review.

2022-05-12 11:44 UTC, tpazderka approved these changes

2022-05-12 11:45 UTC, closed without merging

2022-05-12 11:46 UTC, infohash commented
When the new version will be released?